### ISSUE TITLE
大佬还会更新吗

### ISSUE THREAD

**Issue by pwh-pwh** [0x00000003/AndroidReverseAndSecurity#1]
写得很深入,mark了，期待更新

**Comment by 0x00000003** [comment]
可能吧，微信功能之前专门全部都弄(学习)了一遍，这个是笔记整理了一下，随手记录了一篇

**Comment by pwh-pwh** [comment]
> 可能吧，微信功能之前专门全部都弄(学习)了一遍，这个是笔记整理了一下，随手记录了一篇 

大佬，8.0.40微信，用你的教程里面的思路。已经找不到发送图片的方法了。可以提供一下新的思路吗，有偿也可以。

**Comment by Lxz233** [comment]
大佬wxid 读取是  null，怎么解决

**Comment by 0x00000003** [comment]
你那个人的信息没有载入吧，有些内容的获取需要去触发一次载入

**Comment by Lxz233** [comment]
> 你那个人的信息没有载入吧，有些内容的获取需要去触发一次载入

感谢回复。
 我用的模块是wxrecord  怎么去出发载入。教程没找到。
